set clipboard="unnamedplus" 
set number 
set relativenumber 
set autoindent 
set expandtab 
set shiftround 
set shiftwidth=2
set smarttab 
set tabstop=2
set hlsearch 
set ignorecase 
set incsearch 
set smartcase 
set lazyredraw 
set linebreak 
set encoding=utf-8
set scrolloff=5
set sidescrolloff=5
set laststatus=2
set ruler 
set wildmenu 
set errorbells 
set mouse=a
set backspace="indent,eol,start"
set confirm 
set history=1000
set completeopt=menuone,noinsert,noselect
set splitright 
set splitbelow 
set hidden 
set backup 
set writebackup 
set signcolumn="yes:1"
set cmdheight=1
set updatetime=1000
set swapfile 
set termguicolors 
